### ISSUE TITLE
Missing Processed Data

### ISSUE THREAD

**Issue by yw0208** [LvXinTao/HIMO_dataset#8]
Hi,
There are many key preproced files missing, which makes both training and evaluation impossible. Could you release these files?
Thank you!
```
self.data_path=osp.join(args.data_dir,'processed_{}'.format(self.obj),f'{split}.h5')
self.data_path=osp.join(args.data_dir,'processed_{}'.format(self.obj),f'{split}.h5')
self.obj_bps_path=osp.join(args.data_dir,'processed_{}'.format(self.obj),'object_bps.npz')
self.obj_sampled_verts_path=osp.join(args.data_dir,'processed_{}'.format(self.obj),'sampled_obj_verts.npz')
self.w_vectorizer=WordVectorizer(osp.join(self.args.data_dir,'glove'),'himo_vab')
```

**Comment by liangxuy** [comment]
Sorry for the delay. We have released the processed data, please refer to https://github.com/LvXinTao/HIMO_dataset?tab=readme-ov-file#news.

**Comment by Dekai21** [comment]
> Sorry for the delay. We have released the processed data, please refer to https://github.com/LvXinTao/HIMO_dataset?tab=readme-ov-file#news.

Hi @liangxuy, thanks for sharing the processed data. However, I noticed that the data used in the line `self.w_vectorizer = WordVectorizer(osp.join(self.args.data_dir, 'glove'), 'himo_vab')` is still missing. Would it be possible to make this data available as well?
